<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Change Password</title>
	<?php $this->assets->outputCss(); ?>
</head>
<body>
	<div id="banner">
		<p>Admin Page</p>
	</div>
	<div id="content" style="margin-bottom: 40px;">
		<div id="aside-left">
			<ul>
				<li class="active">
					<?php echo $this->tag->linkTo("manager/index","Home"); ?></a>
				</li>
				<li>
					<?php echo $this->tag->linkTo("manager/edit","Edit Profile"); ?></a>
				</li>
				<li>
					<?php echo $this->tag->linkTo("manager/recent","Recent Login"); ?></a>
				</li>
				<li>
					<?php echo $this->tag->linkTo("manager/users","Manager Member"); ?></a>
				</li>
			</ul>
		</div>
		<div id="main">
			<div class="welcome">
				<p style="font-size: 28px; font-weight: 500;">
					Chào bạn : <?php echo $user->nick_name ?>
				</p>
				<p>
					Nhập thông tin để edit profile của bạn
				</p>
				<br>
				<?php echo isset($mess) ? $mess : "" ?>
			</div>
			<div id="recent">
				<?php echo $this->tag->form("manager/editted"); ?>

					<p class="form-group">
						<label for="old">Old Password</label>
						<br>
						<?php echo $this->tag->passwordField("old"); ?>
					</p>

					<p class="form-group">
						<label for="new">New Password</label>
						<br>
						<?php echo $this->tag->passwordField("new"); ?>
					</p>

					<p class="form-group">
						<?php echo $this->tag->submitButton("Done"); ?>
					</p>

				</form>
			</div>
			<div id="logout">
				<?php echo $this->tag->linkTo("manager/logout", "Logout") ?>
			</div>
		</div>
	</div>
</body>
</html>