<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<?php $this->assets->outputCss(); ?>
	<style type="text/css">
		li > a {
			color: #222;
			text-decoration: none;
		}
		li > a:hover {
			text-decoration: underline;
		}
	</style>
</head>
<body>
	<div id="root">
		<h2>Nav Root</h2>
		<ul>
			<li><?php echo $this->tag->linkTo("login", "Login Here"); ?> </li>
			<li><?php echo $this->tag->linkTo("manager", "My Recent"); ?></li>
			<li><?php echo $this->tag->linkTo("register", "Register Here") ?></li>
		</ul>
	</div>
</body>
</html>